#!/bin/sh
# created by Federico on 16.03.2017
# start and stop Signaling Server
### BEGIN INIT INFO
# Provides:          signalingServer
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     5
# Default-Stop:      0 1 2 3 4 6
# Short-Description: Start Signaling Server Daemon at boot time
# Description:       Enable service provided by Daemon.
### END INIT INFO
SERVICE_NAME=signalingServer
PATH_TO_JAR=/home/pi/server/signalingServer/SignalingServer.jar
PID_PATH_NAME=/var/run/SignalingServer.pid
case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME ]; then
            sudo java -jar $PATH_TO_JAR &
            echo $! > $PID_PATH_NAME
            echo signalingServer PID: $!
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stopping ...";
            kill $PID;
            echo "$SERVICE_NAME stopped ...";
            rm $PID_PATH_NAME
            echo "$SERVICE_NAME starting ..."
            sudo java -jar $PATH_TO_JAR &
            echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
esac

